In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2723, 3679, 7974, 570],
 [2723, 3679, 7974, 9494],
 [2723, 9168, 7974, 6057],
 [4197, 6963, 7525, 2707, 5213],
 [4197, 6963, 7525, 2707, 4412],
 [8161, 2723, 7371, 7974, 3539],
 [1874, 1908, 2695, 2707]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2723 3679 7974  570]
 [   0    0    0    0 2723 3679 7974 9494]
 [   0    0    0    0 2723 9168 7974 6057]
 [   0    0    0 4197 6963 7525 2707 5213]
 [   0    0    0 4197 6963 7525 2707 4412]
 [   0    0    0 8161 2723 7371 7974 3539]
 [   0    0    0    0 1874 1908 2695 2707]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Ashok\Desktop\project\Deep Learning\RNN\myevn\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step


array([[[ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.02107681,  0.02186411,  0.02826161, -0.04444068,
          0.04588703,  0.03965599, -0.03468771, -0.02383108,
         -0.03804781, -0.01076049],
        [-0.02394753, -0.03447404,  0.04267286, -0.02565731,
          0.03934479,  0.0107489 , -0.04752927,  0.01751349,
          0.04293928,  0.03771186],
        [ 0.01502397, -0.03733351, -0.02664392,  0.0

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 2723, 3679, 7974,  570], dtype=int32)

In [17]:
# model.predict(embedded_docs[0])
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[[ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.03885647,  0.0075891 ,  0.03715816, -0.0313877 ,
          0.01504172, -0.00017518, -0.04361608,  0.01469466,
         -0.02558453, -0.0403148 ],
        [ 0.02107681,  0.02186411,  0.02826161, -0.04444068,
          0.04588703,  0.03965599, -0.03468771, -0.02383108,
         -0.03804781, -0.01076049],
        [-0.02394753, -0.03447404,  0.04267286, -0.02565731,
          0.03934479,  0.0107489 , -0.04752927,  0.01751349,
          0.04293928,  0.03771186],
        [ 0.01502397, -0.03733351, -0.02664392,  0.0